# Generated by Django 3.1.5 on 2021-02-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kospipredict',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='기업'),
        ),
    ]
